# @package _global_

defaults:
  - /habitat_baselines: habitat_baselines_rl_config_base
  - /benchmark/nav/goat: goat_hm3d_rgbd_with_semantic
  - /habitat_baselines/rl/policy/obs_transforms:
    - resize_shortest_edge_base
    - center_cropper_base
  - _self_

habitat:
  environment:
    iterator_options:
      max_scene_repeat_steps: 50000
      shuffle: False  # 其实指定场景后有没有shuffle就无所谓了
      # circle: False  # 其实把for循环的len改成筛选后的episode数就可以
      scene_name: "4ok3usBNeis"  # 可选任意场景或者all 但优先级不如命令行参数
  task:
    success_reward: 2.5
    slack_reward: -1e-3
    measurements:
      goat_sub-task_success:
        success_distance:
          1.0
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 1.31, 0]
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 1.31, 0]
          semantic_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 1.31, 0]
        height: 1.41
        radius: 0.17

habitat_baselines:
  torch_gpu_id: 0
  tensorboard_dir: "tb"
  video_dir: "video_dir"
  test_episode_count: -1
  eval_ckpt_path_dir: "data/new_checkpoints"
  num_environments: 1
  checkpoint_folder: "data/new_checkpoints"
  trainer_name: "ddppo"
  num_updates: 270000
  log_interval: 10
  num_checkpoints: 100
  # Force PyTorch to be single threaded as
  # this improves performance considerably
  force_torch_single_threaded: True

  eval:
    split: "minival"
